### ISSUE TITLE
panic: index out of range in network.LimitPoolSize()

### ISSUE THREAD

**Issue by piotrnar** [piotrnar/gocoin#33]
> Mined block 510809
> main panic recovered: runtime error: index out of range
goroutine 1 [running]:
runtime/debug.Stack(0xc477893550, 0x2, 0x2)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
main.main.func1()
        /home/ssdn/GOPATH/src/github.com/piotrnar/gocoin/client/main.go:267 +0x134
panic(0x7bce20, 0xe6bec0)
        /usr/local/go/src/runtime/panic.go:505 +0x229
github.com/piotrnar/gocoin/client/network.LimitPoolSize(0x1cdef9d8)
        /home/ssdn/GOPATH/src/github.com/piotrnar/gocoin/client/network/txpool_sort.go:169 +0x649
github.com/piotrnar/gocoin/client/network.ExpireTxs()
        /home/ssdn/GOPATH/src/github.com/piotrnar/gocoin/client/network/txpool_sort.go:469 +0xcd
github.com/piotrnar/gocoin/client/network.NetworkTick()
        /home/ssdn/GOPATH/src/github.com/piotrnar/gocoin/client/network/tick.go:446 +0x615
main.main()
        /home/ssdn/GOPATH/src/github.com/piotrnar/gocoin/client/main.go:423 +0x9e0

**Comment by piotrnar** [comment]
its fixed on the HEAD
