### ISSUE TITLE
crash upon completing initial sync

### ISSUE THREAD

**Issue by jlopp** [piotrnar/gocoin#46]
I just ran a full sync with the following options:

LastTrustedBlock:"00000000839a8e6886ab5951d76f411475428afc90947ee320161bbf18eb6048"
AllBalances.AutoLoad:false
UTXOSave.SecondsToTake:0

After the sync had completed, gocoin crashed with:

```
> panic: runtime error: integer divide by zero

goroutine 1652364922 [running]:
github.com/piotrnar/gocoin/lib/utxo.(*UnspentDB).save(0xc000c44480)
	/home/jameson/go/src/github.com/piotrnar/gocoin/lib/utxo/unspent_db.go:267 +0xc6e
created by github.com/piotrnar/gocoin/lib/utxo.(*UnspentDB).Save
	/home/jameson/go/src/github.com/piotrnar/gocoin/lib/utxo/unspent_db.go:446 +0x8e
```

**Comment by jlopp** [comment]
If I restart gocoin, it spends an hour importing the blocks and then crashes with the same error.

**Comment by piotrnar** [comment]
Sorry, it's probably because you changed `SecondsToTake` in the config file to 0.
I'll fix it so such value is properly handled, but in the meantime you may want to change it to 1.

**Comment by jlopp** [comment]
Confirmed that this fixed the problem.

**Comment by piotrnar** [comment]
OK, thanks.

Just mind that using 0 as the value of `UTXOSave.SecondsToTake` might make your system unpleasantly slow each time the new UTXO.db is being saved to disk (which happens after each `UTXOSave.BlocksToHold` new blocks)

Although, the whole process should then last not more than 20 seconds, each time.
