### ISSUE TITLE
panic upon receiving a corrupt block

### ISSUE THREAD

**Issue by piotrnar** [piotrnar/gocoin#56]
```
> NewTx failed
Corrupt block received from 34.74.46.5:8333 NewTx failed
GetMerkle(): tx missing 0


********************** THIS SHOULD NOT HAPPEN **********************
Please report by sending email to piotr@gocoin.pl
or by logging new issue at https://github.com/piotrnar/gocoin/issues

Make sure to include the data below:

runtime error: invalid memory address or nil pointer dereference
goroutine 3474354 [running]:
runtime/debug.Stack(0x151ef40, 0xc000010018, 0xc19c42b788)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/piotrnar/gocoin/client/network.(*OneConnection).Run.func1()
        /Users/piotr/gocoin/client/network/tick.go:593 +0x36c
panic(0x141c560, 0x17faea0)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/piotrnar/gocoin/lib/btc.(*Tx).IsCoinBase(0x0, 0xfa36dabbeb826c8e)
        /Users/piotr/gocoin/lib/btc/tx.go:313 +0x26
github.com/piotrnar/gocoin/lib/chain.(*Chain).PostCheckBlock(0xc00015a240, 0xc0b5f79d40, 0x5c1b126c4f00b53d, 0xc24a17a438)
        /Users/piotr/gocoin/lib/chain/block_check.go:149 +0x8a
github.com/piotrnar/gocoin/client/network.netBlockReceived(0xc20e850000, 0xc1aa77c000, 0x1207ec, 0x1207ec)
        /Users/piotr/gocoin/client/network/data.go:184 +0x2c5
github.com/piotrnar/gocoin/client/network.(*OneConnection).Run(0xc20e850000)
        /Users/piotr/gocoin/client/network/tick.go:727 +0x6ee
github.com/piotrnar/gocoin/client/network.DoNetwork.func1(0xc1851c74d0, 0xc20e850000)
        /Users/piotr/gocoin/client/network/tick.go:234 +0x3fa
created by github.com/piotrnar/gocoin/client/network.DoNetwork
        /Users/piotr/gocoin/client/network/tick.go:215 +0x24b


The node will likely malfunction now - it is advised to restart it.
************************ END OF REPORT ****************************

```

**Comment by piotrnar** [comment]
This could only have happened if `len(bl.Txs)` was non zero, but `bl.Txs` was **nil**...
